# Generated by Django 3.2.1 on 2022-12-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbot', '0005_auto_20221229_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
